# Generated by Django 4.2.7 on 2024-01-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="address_line_1",),
        migrations.RemoveField(model_name="userprofile", name="address_line_2",),
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(1, "Vendor"), (2, "Customer")], null=True
            ),
        ),
    ]
