# Generated by Django 4.2.7 on 2024-01-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendor", "0001_initial"),
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="FoodItems", new_name="FoodItem",),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
    ]
