# Generated by Django 4.2.7 on 2024-01-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_rename_fooditems_fooditem_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="slug",
            field=models.SlugField(
                default=models.CharField(max_length=100, unique=True),
                max_length=100,
                unique=True,
            ),
        ),
    ]
