# Generated by Django 4.2.7 on 2024-02-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_fooditem_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="slug",
            field=models.SlugField(default="", max_length=100, unique=True),
        ),
    ]
